CREATE_TABLES_SCRIPT = """

CREATE TABLE IF NOT EXISTS Sites (
    "Id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Icms" TEXT,
    "Difal" TEXT,
    "St" TEXT,
    "Icau" TEXT,
    "Fot" TEXT,
    "Ican" TEXT,
    "Created_At" TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Lojas (
    "Id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Filial" TEXT NOT NULL,
    "Uf" TEXT NOT NULL,
    "Cnpj" TEXT UNIQUE NOT NULL,
    "Ie" TEXT UNIQUE NOT NULL,
    "Site_Id" INTEGER NOT NULL,
    "Created_At" TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(Site_Id) REFERENCES Sites(Id)
);

CREATE TABLE IF NOT EXISTS Guias (
    "Id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Loja_Id" INTEGER NOT NULL,
    "Site_Id" INTEGER NOT NULL,
    "Periodo" DATETIME NOT NULL,
    "Vencimento" DATETIME NOT NULL,
    "Tipo" TEXT NOT NULL,
    "Valor" REAL NOT NULL,
    "Fcp" REAL NOT NULL,
    "Created_At" TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(Loja_Id) REFERENCES Lojas(Id),
    FOREIGN KEY(Site_Id) REFERENCES Sites(Id)
);

CREATE TABLE IF NOT EXISTS NotasGuia (
    "Id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Numero" TEXT NOT NULL,
    "Guia_Id" int NOT NULL,
    "Created_At" TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(Guia_Id) REFERENCES Guias(Id)
);

CREATE TABLE IF NOT EXISTS FretesGuia (
    "Id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Numero" TEXT NOT NULL,
    "Guia_Id" int NOT NULL,
    "Created_At" TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(Guia_Id) REFERENCES Guias(Id)
);
"""
